name: Deploy Frontend Staging

on:
  workflow_run:
    workflows: [Build Frontend]
    types: [completed]
    branches: [staging]
      
jobs: 
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/staging') }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Debug Event Details
        run: |
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"

      - run: echo 'The triggering workflow passed'
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - run: npm install
      - run: npm run build
