name: Deploy Backend Staging

on:
  workflow_run:
    workflows: [Build Backend]
    types: [completed]
    branches: [staging]
      
jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name ==
      'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Details
        run: |
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - run: >
          echo "The triggering workflow commit ID is: ${{
          github.event.workflow_run.head_commit.id }}"
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
